# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beidou.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(742, 427)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.date_line = QtWidgets.QLineEdit(self.centralwidget)
        self.date_line.setObjectName("date_line")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.date_line)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.time_line = QtWidgets.QLineEdit(self.centralwidget)
        self.time_line.setObjectName("time_line")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.time_line)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.longitude_line = QtWidgets.QLineEdit(self.centralwidget)
        self.longitude_line.setObjectName("longitude_line")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.longitude_line)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.latitude_line = QtWidgets.QLineEdit(self.centralwidget)
        self.latitude_line.setObjectName("latitude_line")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.latitude_line)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.altitude_line = QtWidgets.QLineEdit(self.centralwidget)
        self.altitude_line.setObjectName("altitude_line")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.altitude_line)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ic_wait_time = QtWidgets.QLCDNumber(self.centralwidget)
        self.ic_wait_time.setObjectName("ic_wait_time")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ic_wait_time)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.signal_line = QtWidgets.QLineEdit(self.centralwidget)
        self.signal_line.setObjectName("signal_line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.signal_line)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.addr_line = QtWidgets.QLineEdit(self.centralwidget)
        self.addr_line.setObjectName("addr_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.addr_line)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_area = QtWidgets.QTextEdit(self.centralwidget)
        self.message_area.setObjectName("message_area")
        self.verticalLayout.addWidget(self.message_area)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.send_message_line = QtWidgets.QLineEdit(self.centralwidget)
        self.send_message_line.setObjectName("send_message_line")
        self.horizontalLayout_2.addWidget(self.send_message_line)
        self.send_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout_2.addWidget(self.send_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 742, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "北斗系统"))
        self.label_4.setText(_translate("MainWindow", "定位日期"))
        self.label_2.setText(_translate("MainWindow", "定位时间"))
        self.label_5.setText(_translate("MainWindow", "经度"))
        self.label_6.setText(_translate("MainWindow", "纬度"))
        self.label_7.setText(_translate("MainWindow", "高度"))
        self.label_3.setText(_translate("MainWindow", "IC等待时间"))
        self.label_8.setText(_translate("MainWindow", "信号强度"))
        self.label.setText(_translate("MainWindow", "本机地址"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.send_btn.setText(_translate("MainWindow", "发送"))

